### ISSUE TITLE
Misc compile failures due to inaccurate version bounds on `base`

### ISSUE THREAD

**Issue by hvr** [mvoidex/hformat#2]
As can be seen in the screenshots below, the recent `hformat` releases are affected by compiler failures (which unfortunately propagate to packages depending on `hformat`, most notably `hsdev` which I've been seeing users reporting failures with)

In my function as Hackage Trustee, I've already fixed up the incorrect metadata via revisions for the affected releases:

 - https://hackage.haskell.org/package/hformat-0.3.0.0/revisions/
 - https://hackage.haskell.org/package/hformat-0.3.1.0/revisions/
 - https://hackage.haskell.org/package/hformat-0.3.2.0/revisions/
 - https://hackage.haskell.org/package/hformat-0.3.3.0/revisions/

you can review the latest buildreport at https://matrix.hackage.haskell.org/package/hformat

If you're intentionally dropping support for base-4.8, please make sure that future releases of `hformat` have `base >= 4.9` as lower bound; if you want to restore compatibility w/ GHC 7.10.3 & base-4.8, you can add a conditional dependency such as

```
  if !impl(ghc >= 8.0)
     build-depends: semigroups >= 0.18.2 && < 0.19
```

to your `.cabal` file.

Please consider using something like https://github.com/haskell-CI/haskell-ci to help detect such issues in future.

If you have any questions please let me know!

----

![](https://user-images.githubusercontent.com/285533/44511593-57153100-a6b8-11e8-91cd-6ff38353567b.png)

----

![](https://user-images.githubusercontent.com/285533/44511573-4bc20580-a6b8-11e8-9bdd-3377c20947b9.png)

**Comment by mvoidex** [comment]
Thanks!
Uploaded 0.3.3.1, added 7.10.3 to travis
